name: Attach ZIP Asset on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Protector.Net
        run: |
          zip -r protector_net.zip . \
            -x .git/** \
            -x .github/**

      - name: Upload ZIP asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: protector_net.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
