name: Attach ZIP Asset on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Protector.Net
        run: |
          cd custom_components
          zip -r ../protector_net.zip protector_net
          echo "ASSET=protector_net.zip" >> $GITHUB_ENV

      - name: Upload ZIP Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
