name: Attach Protector.Net ZIP on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Protector.Net
        # move into the folder that *contains* your integration files:
        run: |
          cd custom_components/protector_net
          # zip up everything *in* this folder into a ZIP whose root is those files:
          zip -r __artifact__.zip . 
          # move it back to workspace root and register:
          mv __artifact__.zip $GITHUB_WORKSPACE/protector_net.zip
          echo "ASSET=protector_net.zip" >> $GITHUB_ENV

      - name: Upload ZIP Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
